version: 0.0
os: linux

files:
  - source: miniproject4-spring/miniproject04/build/libs/miniproject04-0.0.1-SNAPSHOT.jar
    destination: /home/ubuntu/app
    overwrite: true

hooks:
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 30
      runas: ubuntu

  ApplicationStart:
    - location: scripts/start.sh
      timeout: 60
      runas: ubuntu
